@extends('layouts.app')
@section('content')
<div class="grid gap-8 lg:grid-cols-3"><article class="lg:col-span-2"><div class="overflow-hidden rounded-3xl">
    <img
        src="{{ asset('images/' . $campaign->image()) }}"
        alt="{{ $campaign->title }}"
        class="aspect-video w-full object-cover"
    >
</div><h1 class="mt-6 text-3xl font-bold">{{ $campaign->title }}</h1><p class="mt-2 text-slate-500">{{ $campaign->location }} · {{ $campaign->category->name }} · oleh {{ $campaign->fundraiser->name }}</p><div class="mt-6 h-4 overflow-hidden rounded-full bg-slate-100"><div class="h-full bg-brand-600" style="width: {{ $campaign->progressPercentage() }}%"></div></div><p class="mt-2 font-semibold">Rp {{ number_format($campaign->collected_amount,0,',','.') }} terkumpul dari Rp {{ number_format($campaign->target_amount,0,',','.') }}</p><section class="card mt-6"><h2 class="text-xl font-bold">Cerita Campaign</h2><p class="mt-3 whitespace-pre-line leading-7">{{ $campaign->story }}</p></section><section class="card mt-6"><h2 class="text-xl font-bold">Timeline Update</h2>@forelse($campaign->updates as $update)<div class="mt-4 border-l-4 border-brand-500 pl-4"><p class="font-semibold">{{ $update->title }}</p><p class="text-sm text-slate-500">{{ optional($update->published_at)->format('d M Y') }}</p><p>{{ $update->content }}</p></div>@empty<p class="mt-3 text-slate-500">Belum ada update.</p>@endforelse</section><section class="card mt-6"><h2 class="text-xl font-bold">Transparansi Dana</h2>@foreach($campaign->transparencyReports as $report)<div class="mt-4 rounded-xl bg-slate-50 p-4"><p class="font-semibold">{{ $report->title }} - Rp {{ number_format($report->amount_used,0,',','.') }}</p><p class="text-sm text-slate-600">{{ $report->description }}</p></div>@endforeach</section></article><aside><form class="card sticky top-4" method="post" enctype="multipart/form-data" action="{{ route('campaigns.donate',$campaign) }}">@csrf<h2 class="text-xl font-bold">Donasi Manual</h2><p class="mt-2 text-sm text-slate-600">Transfer ke rekening BSI 1234567890 a.n. Yayasan Sosial Sumsel Peduli lalu upload bukti transfer.</p><input class="input" name="donor_name" placeholder="Nama donatur" value="{{ old('donor_name', auth()->user()->name ?? '') }}"><input class="input" name="donor_email" placeholder="Email" value="{{ old('donor_email', auth()->user()->email ?? '') }}"><input class="input" name="amount" type="number" min="10000" placeholder="Nominal"><input class="input" name="bank_name" placeholder="Bank pengirim"><input class="input" name="account_name" placeholder="Nama rekening"><input class="input" name="transfer_date" type="date"><textarea class="input" name="message" placeholder="Pesan opsional"></textarea><input class="input" name="proof" type="file" accept="image/*,application/pdf"><button class="btn-primary mt-4 w-full">Kirim Bukti Donasi</button>@if($errors->any())<ul class="mt-3 text-sm text-red-600">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul>@endif</form></aside></div>
@endsection
